/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSimulationRouteImport } from './routes/api/simulation'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiObservabilityLogsRouteImport } from './routes/api/observability.logs'
import { Route as ApiCreditScoresAssessmentIdRouteImport } from './routes/api/credit-scores.$assessmentId'
import { Route as ApiAssessmentsAssessmentIdRouteImport } from './routes/api/assessments.$assessmentId'
import { Route as ApiAssessmentsAssessmentIdStatusRouteImport } from './routes/api/assessments.$assessmentId.status'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationRoute = ApiSimulationRouteImport.update({
  id: '/api/simulation',
  path: '/api/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilityLogsRoute = ApiObservabilityLogsRouteImport.update({
  id: '/api/observability/logs',
  path: '/api/observability/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditScoresAssessmentIdRoute =
  ApiCreditScoresAssessmentIdRouteImport.update({
    id: '/api/credit-scores/$assessmentId',
    path: '/api/credit-scores/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssessmentsAssessmentIdRoute =
  ApiAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => ApiAssessmentsRoute,
  } as any)
const ApiAssessmentsAssessmentIdStatusRoute =
  ApiAssessmentsAssessmentIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAssessmentsAssessmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/logs': typeof LogsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/logs': typeof LogsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/logs': typeof LogsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/logs'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/assessments/$assessmentId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/logs'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/assessments/$assessmentId/status'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/logs'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/assessments/$assessmentId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  LogsRoute: typeof LogsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSimulationRoute: typeof ApiSimulationRoute
  ApiCreditScoresAssessmentIdRoute: typeof ApiCreditScoresAssessmentIdRoute
  ApiObservabilityLogsRoute: typeof ApiObservabilityLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation': {
      id: '/api/simulation'
      path: '/api/simulation'
      fullPath: '/api/simulation'
      preLoaderRoute: typeof ApiSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/logs': {
      id: '/api/observability/logs'
      path: '/api/observability/logs'
      fullPath: '/api/observability/logs'
      preLoaderRoute: typeof ApiObservabilityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit-scores/$assessmentId': {
      id: '/api/credit-scores/$assessmentId'
      path: '/api/credit-scores/$assessmentId'
      fullPath: '/api/credit-scores/$assessmentId'
      preLoaderRoute: typeof ApiCreditScoresAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$assessmentId': {
      id: '/api/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/api/assessments/$assessmentId'
      preLoaderRoute: typeof ApiAssessmentsAssessmentIdRouteImport
      parentRoute: typeof ApiAssessmentsRoute
    }
    '/api/assessments/$assessmentId/status': {
      id: '/api/assessments/$assessmentId/status'
      path: '/status'
      fullPath: '/api/assessments/$assessmentId/status'
      preLoaderRoute: typeof ApiAssessmentsAssessmentIdStatusRouteImport
      parentRoute: typeof ApiAssessmentsAssessmentIdRoute
    }
  }
}

interface ApiAssessmentsAssessmentIdRouteChildren {
  ApiAssessmentsAssessmentIdStatusRoute: typeof ApiAssessmentsAssessmentIdStatusRoute
}

const ApiAssessmentsAssessmentIdRouteChildren: ApiAssessmentsAssessmentIdRouteChildren =
  {
    ApiAssessmentsAssessmentIdStatusRoute:
      ApiAssessmentsAssessmentIdStatusRoute,
  }

const ApiAssessmentsAssessmentIdRouteWithChildren =
  ApiAssessmentsAssessmentIdRoute._addFileChildren(
    ApiAssessmentsAssessmentIdRouteChildren,
  )

interface ApiAssessmentsRouteChildren {
  ApiAssessmentsAssessmentIdRoute: typeof ApiAssessmentsAssessmentIdRouteWithChildren
}

const ApiAssessmentsRouteChildren: ApiAssessmentsRouteChildren = {
  ApiAssessmentsAssessmentIdRoute: ApiAssessmentsAssessmentIdRouteWithChildren,
}

const ApiAssessmentsRouteWithChildren = ApiAssessmentsRoute._addFileChildren(
  ApiAssessmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  LogsRoute: LogsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAssessmentsRoute: ApiAssessmentsRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSimulationRoute: ApiSimulationRoute,
  ApiCreditScoresAssessmentIdRoute: ApiCreditScoresAssessmentIdRoute,
  ApiObservabilityLogsRoute: ApiObservabilityLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
